#!/bin/bash

set -x
exec 2> /tmp/debugoutdataload

ps -ef | grep geofinder-api | grep -v grep | awk '{print $2}' | xargs kill

if [gremlin-console -e "system.graph('fraud').exists()"]
    then
        gremlin-console -e "system.graph('fraud').drop();"
fi

if [ `hostname` == 'node0' ]
    then
        cqlsh -e "DROP KEYSPACE IF EXISTS simplegeo;" node0

elif [ `hostname` == 'developer-day-node1' ]
    then
        cqlsh -e "DROP KEYSPACE IF EXISTS simplegeo;" node1
fi

rm -rf /var/lib/cassandra/data/simplegeo

# setup graph data
# dse fs "rm -r /data"

# Cleanup
rm -f /tmp/SDDemos/simplegeo_locations_SSTables-DSE5.1.tgz
rm -f /tmp/SDDemos/put PS_20174392719_1491204439457_log.csv
