#!/bin/bash
set -x
exec 2> /tmp/debugoutnotebooks


# ps -ef | grep studio-server | grep -v grep | awk '{print $2}' | xargs kill
# sleep 10
# rm -rf ~/.datastax_studio
# cd /tmp/datastax-studio-*
# sudo bin/server.sh &
# cd /tmp/SDDemos
# sleep 50

FILENAME1=Dev_Day_Core_Cassandra_First_Touch.tar
FILENAME2=Dev_Day_DSE_Graph_Example_Fraud.tar
FILENAME3=Dev_Day_Working_with_SparkSQL.tar

#Get content
curl -O 'https://s3.amazonaws.com/datastaxtraining/OverviewSession/'$FILENAME1
curl -O 'https://s3.amazonaws.com/datastaxtraining/OverviewSession/'$FILENAME2
curl -O 'https://s3.amazonaws.com/datastaxtraining/OverviewSession/'$FILENAME3


# Fetch IP Address
IP=$(ifconfig | awk '/inet/ { print $2 }' | egrep -v '^fe|^127|^192|^172|::' | head -1)
IP=${IP#addr:}

if [[ $HOSTNAME == "node"* ]] ; then
    #rightscale
    IP=$(grep $(hostname)_ext /etc/hosts | awk '{print $1}')
fi

curl -H "Accept-Encoding: gzip" -X POST -F 'file=@'$FILENAME1 http://"$IP":9091/api/v1/notebooks/import &> /dev/null
curl -H "Accept-Encoding: gzip" -X POST -F 'file=@'$FILENAME2 http://"$IP":9091/api/v1/notebooks/import &> /dev/null
curl -H "Accept-Encoding: gzip" -X POST -F 'file=@'$FILENAME3 http://"$IP":9091/api/v1/notebooks/import &> /dev/null


#lagecy code 
# the studio folder gets unpacked into correct location
# if [ `hostname` == 'node0' ]
#     then
#         pushd /; tar -zxvf /tmp/SDDemos/notebooks.tar; popd
# elif [ `hostname` == 'node1' ]
#     then
#         pushd /home/ubuntu; tar -zxvf /tmp/SDDemos/notebooks.tar; popd
#         mv /home/ubuntu/root/* /home/ubuntu/
# fi
# ps -ef | grep studio-server | grep -v grep | awk '{print $2}' | xargs kill
# sleep 10
# cd /tmp/datastax-studio-*
# bin/server.sh &
