#!/bin/bash
set -x
exec 2> /tmp/debugoutnotebooks
# create Cassandra Schema
if [ `hostname` == 'node0' ]
    then
        cp /tmp/SDDemos/*-nb.tar /tmp/datastax-studio*/examples/
elif [ `hostname` == 'node1' ]
    then
        cp /tmp/SDDemos/*-nb.tar /tmp/datastax-studio*/examples/
fi
